name: Test
on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-13, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies packages for linux
        if: runner.os == 'Linux'
        run: sudo apt-get install ocl-icd-opencl-dev opencl-headers
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v .
      - name: Show OpenCL devices informations
        run: go run . -info -all
